import todoFactory from './todoFactory';
import projectFactory from './projectFactory';
import homepage from './homepage';
import projectButtonActions from './projectButton';
import projectIndexToPage from './projectIndex';
import todoButtonActions from './todoButton';
import todoIndexToPage from './todoIndex';
import todoCancelButton from './todoCancelButton';
import projectCancelButton from './projectCancelButton';
import deleteProject from './deleteProject';
import defaultProject from './defaultProject';

homepage();
projectButtonActions();
projectIndexToPage();
todoButtonActions();
todoIndexToPage();
todoCancelButton();
projectCancelButton();
defaultProject();
deleteProject();
